Container Location: /home/cisco/cxta-bpa/examples
Free Space: Filesystem               Size  Used Avail Use% Mounted on, overlay                   45G   22G   23G  50%
  /, tmpfs                     64M     0   64M   0% /dev, tmpfs                    5.4G     0  5.4G   0%
  /sys/fs/cgroup, /dev/mapper/centos-root   45G   22G   23G  50% /etc/hosts, shm                       64M  8.0K   64M   1%
  /dev/shm
Full Environment: LESSOPEN=| /usr/bin/lesspipe %s, LANGUAGE=C.UTF-8, HOSTNAME=5e6777d05e64,
  SHLVL=1, HOME=/root, OLDPWD=/home/cisco/cxta-bpa, SELENIUM_URL=http://selenium:4444/wd/hub,
  _=/venv/bin/robot, TERM=xterm, COLUMNS=185, PATH=/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin,
  LANG=C.UTF-8, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:,
  LESSCLOSE=/usr/bin/lesspipe %s %s, LC_ALL=C.UTF-8, PWD=/home/cisco/cxta-bpa/examples,
  PYTHONPATH=/home/cisco/cxta-bpa/src, LINES=51
Git Build Info: ''
Git Run Info: 061906b HEAD -> master, origin/master, origin/HEAD oboehmer Mon Oct
  14 12:49:52 2019 +0200
Host OS: ''
Host User: '@'
Pip Freeze: ansible==2.8.1, apipkg==1.5, appdirs==1.4.3, Appium-Python-Client==0.46,
  artifactory==0.1.17, asn1crypto==0.24.0, asyncssh==1.16.1, atomicwrites==1.3.0,
  attrdict==2.0.0, attrs==19.1.0, autopep8==1.3.5, Babel==2.7.0, backports.ssl==0.0.9,
  bcrypt==3.1.7, bleach==3.1.0, cached-property==1.5.1, certifi==2019.6.16, cffi==1.12.3,
  chardet==3.0.4, ciscoconfparse==1.3.39, Click==7.0, cliff==2.15.0, cmd2==0.9.16,
  colorama==0.4.1, coverage==4.5.4, cryptography==2.7, CXTA==0+unknown, Cython==0.28.4,
  dateparser==0.7.1, debtcollector==1.22.0, decorator==4.4.0, defusedxml==0.6.0, dill==0.3.0,
  distro==1.4.0, dnspython==1.16.0, docutils==0.14, dogpile.cache==0.7.1, elasticsearch==5.4.0,
  entrypoints==0.3, et-xmlfile==1.0.1, execnet==1.7.1, exrex==0.10.5, Faker==1.0.1,
  flake8==3.5.0, flake8-blind-except==0.1.1, flake8-builtins==1.4.1, flake8-per-file-ignores==0.8.1,
  flaky==3.3.0, genie==19.5.0, genie.abstract==19.8, genie.conf==19.8, genie.examples==19.6.0,
  genie.harness==19.8, genie.libs.conf==19.8, genie.libs.filetransferutils==19.8,
  genie.libs.ops==19.8, genie.libs.parser==19.8, genie.libs.robot==19.5.0, genie.libs.sdk==19.8,
  genie.libs.telemetry==19.8, genie.metaparser==19.8, genie.ops==19.8, genie.parsergen==19.8,
  genie.predcore==19.8, genie.telemetry==19.8, genie.trafficgen==19.8, genie.utils==19.8,
  gitdb2==2.0.5, GitPython==3.0.2, hltapi==19.7, html5lib==1.0.1, htmlmin==0.1.12,
  idna==2.6, importlib-metadata==0.20, iso8601==0.1.12, isodate==0.6.0, ixia-api==2019.7.17,
  IxNetwork==9.0.1915.16, ixnetwork-restpy==1.0.21, jdcal==1.4.1, jeepney==0.4.1,
  Jinja2==2.10, jmespath==0.9.4, jq==0.1.6, jsonpatch==1.24, jsonpath==0.80, jsonpath-rw==1.4.0,
  jsonpath-rw-ext==1.2.2, jsonpickle==1.2, jsonpointer==2.0, jsonschema==3.0.2, junit-xml==1.8,
  keyring==15.1.0, keystoneauth1==3.17.0, livereload==2.6.1, Logbook==1.5.2, lxml==4.3.3,
  Markdown==3.1.1, MarkupSafe==1.1.1, mccabe==0.6.1, mkdocs==1.0.4, mkdocs-material==4.0.1,
  more-itertools==7.2.0, msgpack==0.6.1, munch==2.3.2, ncclient==0.6.6, netaddr==0.7.19,
  netifaces==0.10.9, ntlm-auth==1.4.0, openpyxl==2.5.9, openstacksdk==0.35.0, os-service-types==1.7.0,
  osc-lib==1.14.0, oslo.config==6.11.1, oslo.i18n==3.24.0, oslo.serialization==2.29.2,
  oslo.utils==3.41.1, paramiko==2.6.0, passlib==1.7.1, pathlib==1.0.1, pathmatch==0.2.1,
  pathspec==0.5.9, pbr==5.4.3, pep562==1.0, pexpect==3.2, pika==0.10.0, Pillow==6.1.0,
  pkginfo==1.5.0.1, pluggy==0.12.0, ply==3.11, prettytable==0.7.2, psutil==5.6.3,
  psycopg2==2.6.1, py==1.8.0, pyasn1==0.4.5, pyats==19.5.0, pyats.aereport==19.5.0,
  pyats.aetest==19.5.0, pyats.async==19.5.0, pyats.connections==19.5.0, pyats.datastructures==19.5.0,
  pyats.easypy==19.5.0, pyats.examples==19.5.0, pyats.kleenex==19.5.0, pyats.log==19.5.0,
  pyats.results==19.5.0, pyats.robot==19.5.0, pyats.tcl==19.5.0, pyats.templates==19.5.0,
  pyats.topology==19.5.0, pyats.utils==19.5.0, pycodestyle==2.3.1, pycparser==2.19,
  pyflakes==1.6.0, pyftpdlib==1.5.5, Pygments==2.4.2, pymdown-extensions==6.1, PyNaCl==1.3.0,
  pyOpenSSL==19.0.0, pyparsing==2.4.2, PyPDF2==1.26.0, pyperclip==1.7.0, pyrsistent==0.15.4,
  pyshark==0.4.2.3, pysphere==0.1.7, pytest==4.0.2, pytest-cov==2.5.1, pytest-mock==0.10.1,
  pytest-random-order==1.0.4, pytest-xdist==1.12, python-cinderclient==4.3.0, python-dateutil==2.8.0,
  python-glanceclient==2.16.0, python-keystoneclient==3.20.0, python-novaclient==15.0.0,
  python-openstackclient==3.19.0, pytz==2018.3, pyvmomi==6.0.0, pywinrm==0.3.0, PyYAML==5.1,
  readme-renderer==24.0, recordtype==1.3, redfish==2.0.6, regex==2019.6.8, reportlab==3.5.23,
  requests==2.21.0, requests-ntlm==1.1.0, requests-toolbelt==0.9.1, requestsexceptions==1.4.0,
  rfc3986==1.3.2, robotframework==3.1.2, robotframework-faker==4.2.0, robotframework-requests==0.4.7,
  robotframework-seleniumlibrary==3.3.1, robotframework-sshlibrary==3.1.0, scp==0.10.2,
  SecretStorage==3.1.1, selenium==3.141.0, setproctitle==1.1.10, simplejson==3.16.0,
  singleton-decorator==1.0.0, six==1.12.0, smmap2==2.0.5, spirent-api==2019.3.1501,
  stevedore==1.31.0, terminaltables==3.1.0, text-unidecode==1.2, textfsm==0.4.1, titlecase==0.12.0,
  tmrac==0.1, tornado==6.0.3, tqdm==4.35.0, twine==1.13.0, typing==3.7.4.1, tzlocal==2.0.0,
  unicon==19.7.2, unicon-plugin-pdu==1.0, unicon-plugin-tma==1.1, unicon-plugin-viptela==1.1,
  uniq==2.2.23.40, uniq.apis==2.2.23.40, uniq.apps==2.2.23.40, uniq.clis==2.2.23.40,
  uniq.gv-cli==2.2.23.40, uniq.postgres==2.2.23.40, uniq.testbed==2.2.23.40, uniq.utils==2.2.23.40,
  urllib3==1.24.1, urlparse2==1.1.1, warlock==1.3.3, wcwidth==0.1.7, webencodings==0.5.1,
  websocket-client==0.56.0, wrapt==1.11.2, xhtml2pdf==0.2.3, xmltodict==0.12.0, yamllint==1.17.0,
  yang.connector==3.0.1, yq==2.7.2, zeep==3.4.0, zipp==0.6.0
Pip Show CXTA: 'Name: CXTA, Version: 0+unknown, Summary: This package contains the
  CXTA Robot keyword library and infrastructure., Home-page: https://wwwin-github.cisco.com/AS-Community/CXTA,
  Author: Cisco Systems - CX, Author-email: N/A, License: Cisco Systems, Inc. - Proprietary
  & Confidential, Location: /venv/lib/python3.6/site-packages, Requires: , Required-by:'
Supplied Args:
- /venv/bin/robot
- 4.6.13_UI.robot
